import mon1 from "../assets/dishs/mon1.jpg"
import mon2 from "../assets/dishs/mon2.jpg"
import mon3 from "../assets/dishs/mon3.jpg"
import mon4 from "../assets/dishs/mon4.jpg"
import mon5 from "../assets/dishs/mon5.jpg"
import mon6 from "../assets/dishs/mon6.jpg"
import mon7 from "../assets/dishs/mon7.jpg"
import mon8 from "../assets/dishs/mon8.jpg"
import mon9 from "../assets/dishs/mon9.jpg"
import { Dish } from "../models/dish"

const fakeListDish:Dish[] = [
              {
                   id: 1,
                   name: "Cơm rang gà quay",
                   des: '',
                   mealTime: 1,
                   price: '$25.99',
                   src: mon1,
                   like: true,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
              },
              {
                   id: 2,
                   name: "Cơm rang dưa bò",
                   des: '',
                   mealTime: 2,
                   price: '$25.99',
                   src: mon2,
                   like: false,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
              },
              {
                   id: 3,
                   name: "Cơm rang cải bò",
                   des: '',
                   mealTime: 3,
                   price: '$25.99',
                   src: mon3,
                   like: true,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
              },
              {
                   id: 4,
                   name: "Salad",
                   des: '',
                   mealTime: 4,
                   price: '$25.99',
                   src: mon4,
                   like: false,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
              },
              {
                   id: 5,
                   name: "Phở xào",
                   des: '',
                   mealTime: 1,
                   price: '$25.99',
                   src: mon5,
                   like: false,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
              },
              {
                   id: 6,
                   name: "Mỳ xào",
                   des: '',
                   mealTime: 2,
                   price: '$25.99',
                   src: mon6,
                   like: false,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
              },
              {
                   id: 7,
                   name: "Cơm rang gà nấm",
                   des: '',
                   mealTime: 3,
                   price: '$25.99',
                   src: mon7,
                   like: true,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
              },
              {
                   id: 8,
                   name: "Cơm rang bò nấm",
                   des: '',
                   mealTime: 4,
                   price: '$20.99',
                   src: mon8,
                   like: false,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
              },
              {
                   id: 9,
                   name: "Cơm chay",
                   des: '',
                   mealTime: 1,
                   price: '$19.99',
                   src: mon9,
                   like: true,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
              },
              {
                   id: 10,
                   name: "Cơm thịt kho tàu",
                   des: '',
                   mealTime: 1,
                   price: '$25.99',
                   src: mon1,
                   like: true,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
              },
              {
                   id: 11,
                   name: "Cơm cá thu",
                   des: '',
                   mealTime: 2,
                   price: '$25.99',
                   src: mon2,
                   like: false,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
              },
              {
                   id: 12,
                   name: "Phở bò tái",
                   des: '',
                   mealTime: 3,
                   price: '$25.99',
                   src: mon3,
                   like: true,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
              },
              {
                   id: 13,
                   name: "Phở bò chín",
                   des: '',
                   mealTime: 4,
                   price: '$25.99',
                   src: mon4,
                   like: false,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
              },
              {
                   id: 14,
                   name: "Phở bò nạm",
                   des: '',
                   mealTime: 1,
                   price: '$25.99',
                   src: mon5,
                   like: false,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
              },
              {
                   id: 15,
                   name: "Bún riêu cua bò giò",
                   des: '',
                   mealTime: 2,
                   price: '$25.99',
                   src: mon6,
                   like: false,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
              },
              {
                   id: 16,
                   name: "Bún riêu cua sườn",
                   des: '',
                   mealTime: 3,
                   price: '$25.99',
                   src: mon7,
                   like: true,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
              },
              {
                   id: 17,
                   name: "Bún riêu cua top mỡ",
                   des: '',
                   mealTime: 4,
                   price: '$20.99',
                   src: mon8,
                   like: false,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
              },
              {
                   id: 18,
                   name: "Bún cá đồng",
                   des: '',
                   mealTime: 1,
                   price: '$19.99',
                   src: mon9,
                   like: true,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
              },
              {
                   id: 19,
                   name: "Bún chả",
                   des: '',
                   mealTime: 1,
                   price: '$19.99',
                   src: mon9,
                   like: true,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
              },
              {
                   id: 20,
                   name: "Bún đậu mắn tôm",
                   des: '',
                   mealTime: 1,
                   price: '$19.99',
                   src: mon9,
                   like: true,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
              },
              {
                   id: 21,
                   name: "Phở gà",
                   des: '',
                   mealTime: 1,
                   price: '$19.99',
                   src: mon9,
                   like: true,
                   check: true,
                   time: '12 mm',
                   star: ' 4.5 / 755',
                   allergenic: 'egg',
                   group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
              },
              {
                            id: 22,
                            name: "Cơm rang gà quay",
                            des: '',
                            mealTime: 1,
                            price: '$25.99',
                            src: mon1,
                            like: true,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
                       },
                       {
                            id: 23,
                            name: "Cơm rang dưa bò",
                            des: '',
                            mealTime: 2,
                            price: '$25.99',
                            src: mon2,
                            like: false,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
                       },
                       {
                            id: 24,
                            name: "Cơm rang cải bò",
                            des: '',
                            mealTime: 3,
                            price: '$25.99',
                            src: mon3,
                            like: true,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
                       },
                       {
                            id: 25,
                            name: "Salad",
                            des: '',
                            mealTime: 4,
                            price: '$25.99',
                            src: mon4,
                            like: false,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
                       },
                       {
                            id: 26,
                            name: "Phở xào",
                            des: '',
                            mealTime: 1,
                            price: '$25.99',
                            src: mon5,
                            like: false,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
                       },
                       {
                            id: 27,
                            name: "Mỳ xào",
                            des: '',
                            mealTime: 2,
                            price: '$25.99',
                            src: mon6,
                            like: false,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
                       },
                       {
                            id: 28,
                            name: "Cơm rang gà nấm",
                            des: '',
                            mealTime: 3,
                            price: '$25.99',
                            src: mon7,
                            like: true,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
                       },
                       {
                            id: 29,
                            name: "Cơm rang bò nấm",
                            des: '',
                            mealTime: 4,
                            price: '$20.99',
                            src: mon8,
                            like: false,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
                       },
                       {
                            id: 30,
                            name: "Cơm chay",
                            des: '',
                            mealTime: 1,
                            price: '$19.99',
                            src: mon9,
                            like: true,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
                       },
                       {
                            id: 31,
                            name: "Cơm thịt kho tàu",
                            des: '',
                            mealTime: 1,
                            price: '$25.99',
                            src: mon1,
                            like: true,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
                       },
                       {
                            id: 32,
                            name: "Cơm cá thu",
                            des: '',
                            mealTime: 2,
                            price: '$25.99',
                            src: mon2,
                            like: false,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
                       },
                       {
                            id: 33,
                            name: "Phở bò tái",
                            des: '',
                            mealTime: 3,
                            price: '$25.99',
                            src: mon3,
                            like: true,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
                       },
                       {
                            id: 34,
                            name: "Phở bò chín",
                            des: '',
                            mealTime: 4,
                            price: '$25.99',
                            src: mon4,
                            like: false,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
                       },
                       {
                            id: 35,
                            name: "Phở bò nạm",
                            des: '',
                            mealTime: 1,
                            price: '$25.99',
                            src: mon5,
                            like: false,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
                       },
                       {
                            id: 36,
                            name: "Bún riêu cua bò giò",
                            des: '',
                            mealTime: 2,
                            price: '$25.99',
                            src: mon6,
                            like: false,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
                       },
                       {
                            id: 37,
                            name: "Bún riêu cua sườn",
                            des: '',
                            mealTime: 3,
                            price: '$25.99',
                            src: mon7,
                            like: true,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
                       },
                       {
                            id: 38,
                            name: "Bún riêu cua top mỡ",
                            des: '',
                            mealTime: 4,
                            price: '$20.99',
                            src: mon8,
                            like: false,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
                       },
                       {
                            id: 39,
                            name: "Bún cá đồng",
                            des: '',
                            mealTime: 1,
                            price: '$19.99',
                            src: mon9,
                            like: true,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
                       },
                       {
                            id: 40,
                            name: "Bún chả",
                            des: '',
                            mealTime: 1,
                            price: '$19.99',
                            src: mon9,
                            like: true,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
                       },
                       {
                            id: 41,
                            name: "Bún đậu mắn tôm",
                            des: '',
                            mealTime: 1,
                            price: '$19.99',
                            src: mon9,
                            like: true,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
                       },
                       {
                            id: 42,
                            name: "Phở gà",
                            des: '',
                            mealTime: 1,
                            price: '$19.99',
                            src: mon9,
                            like: true,
                            check: true,
                            time: '12 mm',
                            star: ' 4.5 / 755',
                            allergenic: 'egg',
                            group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
                       },

         ]
export default fakeListDish;
